- name: Install base packages (Flatpak + video accel + utils)
  ansible.builtin.apt:
    name:
      - flatpak
      - vainfo
      - libva2
      - gstreamer1.0-vaapi
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - intel-media-va-driver
      - i965-va-driver
      - steam-devices
      - htop
      - libdvdcss2
      - python3-pyside6.qtwidgets
      - python3-pyside6.qtgui
      - python3-pyside6.qtcore
    state: present
