- name: Enable multiverse repo for libdvdcss (if not already)
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu noble multiverse"
    state: present
    update_cache: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
