- hosts: localhost
  become: true

  vars_prompt:
    - name: sway_user
      prompt: "Which is the user executing sway?"
      private: false

  vars:
    flatpak_vaapi_apps:
      - rocks.shy.VacuumTube
      - com.github.iwalton3.jellyfin-media-player
      - org.libretro.RetroArch
      - com.valvesoftware.Steam

  roles:
    - packages
    - flatpak
    - sway
    - updates
