---
- name: Configure Fedora SWAY TVBox
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Fetch the default username from /etc/passwd
      ansible.builtin.shell: |
        set -o pipefail
        awk -F: '$3 >= 1000 && $3 < 65534 && $7 != "/usr/sbin/nologin" && $7 != "/bin/false" {print $1}' /etc/passwd | head -n 1
      register: default_user
      changed_when: false

    - name: Set the default username as a fact
      ansible.builtin.set_fact:
        default_username: "{{ default_user.stdout }}"

    - name: Prompt for username with default value
      ansible.builtin.pause:
        prompt: "Enter username for auto login and sway config (default: {{ default_username }})"
      register: sway_user_prompt

    - name: Set the final username
      ansible.builtin.set_fact:
        sway_user: "{{ sway_user_prompt.user_input | default(default_username) }}"

    - name: Debug the entered username
      ansible.builtin.debug:
        msg: "The username entered is {{ sway_user }}"

    # Check if user exists
    - name: Verify that the specified user exists
      ansible.builtin.command: getent passwd {{ sway_user }}
      register: user_check
      ignore_errors: true
      changed_when: false

    - name: Fail if user does not exist
      ansible.builtin.fail:
        msg: "The user '{{ sway_user }}' does not exist."
      when: user_check.rc != 0

    # Check if home directory exists
    - name: Verify that the home directory for the specified user exists
      ansible.builtin.stat:
        path: /home/{{ sway_user }}
      register: home_dir_stat

    - name: Fail if home directory does not exist
      ansible.builtin.fail:
        msg: "The home directory '/home/{{ sway_user }}' does not exist."
      when: not home_dir_stat.stat.exists

  roles:
    - role: base_system
      tags: [system, packages]

    - role: flatpak
      tags: [system, flatpak]

    - role: display_manager
      tags: [desktop, login]

    - role: dvd_autoplay
      tags: [system, multimedia]

    - role: update_manager
      tags: [system, updates]

    - role: user_config
      tags: [desktop, sway]

    - role: host_configuration
      tags: [system, config]
