- hosts: localhost
  become: true

  vars_prompt:
    - name: sway_user
      prompt: "Which is the user executing sway?"
      private: false

  roles:
    - packages
    - flatpak
    - sway
    - updates
