############################################
# Install basic packages
############################################

- name: Get Fedora version
  ansible.builtin.shell: "rpm -E %fedora"
  register: fedora_version
  changed_when: false
  ignore_errors: true
  check_mode: no

# - name: Import RPM Fusion Free GPG key
#   ansible.builtin.rpm_key:
#     key: "https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"

# - name: Import RPM Fusion NON Free GPG key
#   ansible.builtin.rpm_key:
#     key: "https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

- name: Install RPM Fusion free repo
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
    disable_gpg_check: true
    state: present

- name: Install RPM Fusion nonfree repo
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
    disable_gpg_check: true
    state: present

- name: Install base packages
  dnf:
    name:
      - flatpak
      - libva-utils
      - libva
      - gstreamer1-vaapi
      - intel-gpu-tools
      - mesa-dri-drivers
      - mesa-vdpau-drivers-freeworld
      - gnome-text-editor
      - libva-intel-driver
      - python3-tkinter
      - steam-devices
      - htop
    state: present

############################################
# Base config
############################################
- name: Set the hostname
  ansible.builtin.hostname:
    name: "fedora-tvbox"

- name: Set the timezone to Europe/Berlin
  ansible.builtin.command:
    cmd: timedatectl set-timezone Europe/Berlin


############################################
# Install packages for dvd autoplay
############################################
- name: Install rpmfusion tainted repo
  dnf:
    name: rpmfusion-free-release-tainted
    state: present
  #when: install_dvd_autoplay

- name: Install dvd packages
  dnf:
    name:
      - libdvdcss
      - udisks2
      - mpv
    state: present
  #when: install_dvd_autoplay
