- name: Copy auto update script
  ansible.builtin.copy:
    src: fedora-flatpak-auto-update.sh
    dest: /usr/local/bin/fedora-flatpak-auto-update.sh"
    mode: '0755'
  become: true

- name: Copy update execution config
  ansible.builtin.copy:
    src: bbe_update_all.json
    dest: "{{ ansible_env.HOME }}/bbe_update_all.json"
    mode: '0644'
  become: false
  become_user: "{{ ansible_user }}"

- name: Copy big button executor
  ansible.builtin.copy:
    src: big_button_exec.py
    dest: "{{ ansible_env.HOME }}/big_button_exec.py"
    mode: '0755'
  become: false
  become_user: "{{ ansible_user }}"

- name: Create sudoers.d file for passwordless dnf upgrade
  ansible.builtin.copy:
    content: |
      {{ ansible_name }} ALL = NOPASSWD: /usr/bin/dnf upgrade *
    dest: /etc/sudoers.d/90-dnf-upgrade
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  become: true