- name: Create systemd user services directory
  ansible.builtin.file:
    path: "/home/{{ sway_user }}/.config/systemd/user/"
    state: directory
    mode: '0755'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Copy DVD service
  ansible.builtin.copy:
    src: scripts/auto-play-dvd.service
    dest: "/home/{{ sway_user }}/.config/systemd/user/auto-play-dvd.service"
    mode: '0755'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Copy DVD udev rule
  ansible.builtin.copy:
    src: config/99-dvd-autoplay.rules
    dest: "/etc/udev/rules.d/99-dvd-autoplay.rules"
    mode: '0644'

- name: Copy DVD auto-play script
  ansible.builtin.copy:
    src: scripts/auto-dvd-mpv.sh
    dest: "/usr/local/bin/auto-dvd-mpv.sh"
    mode: '0755'
