- name: Apply VAAPI override to flatpak apps
  ansible.builtin.command: >
    flatpak override --env=LIBVA_DRIVER_NAME={{ flatpak_vaapi_driver }} --device=dri {{ item }}
  loop: "{{ flatpak_apps }}"
  changed_when: false
  become_user: "{{ tv_user }}"
