---
- name: Setup flatpak
  ansible.builtin.include_tasks: setup_flatpak.yml

- name: Install Apps
  ansible.builtin.include_tasks: install_apps.yml

- name: Detect VAAPI
  ansible.builtin.include_tasks: vaapi_detection.yml

- name: Apply Overrides
  ansible.builtin.include_tasks: apply_overrides.yml
