############################################
# Install flatpak packages
############################################
- name: Ensure flatpak installed
  dnf:
    name: flatpak
    state: present

- name: Add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - com.github.iwalton3.jellyfin-media-player
      - org.libretro.RetroArch
      - rocks.shy.VacuumTube
    state: present
    become_user: "{{ ansible_user }}"


############################################
# Add overrides
############################################
- name: Detect GPU
  command: lspci -nnk
  register: gpu_info
  changed_when: false

- name: Determine VAAPI driver
  set_fact:
    vaapi_driver: >-
      {% if "Intel" in gpu_info.stdout and "UHD" in gpu_info.stdout %}iHD
      {% elif "Intel" in gpu_info.stdout %}i965
      {% elif "AMD" in gpu_info.stdout or "Radeon" in gpu_info.stdout %}radeonsi
      {% else %}iHD{% endif %}

- name: Show selected VAAPI driver
  debug:
    msg: "Using VAAPI driver: '{{ vaapi_driver }}'"

- name: Apply VAAPI override to flatpak apps
  vars:
    flatpak_vaapi_apps:
      - rocks.shy.VacuumTube
      - com.github.iwalton3.jellyfin-media-player
      - org.libretro.RetroArch
  command: >
    flatpak override --user --env=LIBVA_DRIVER_NAME={{ vaapi_driver }} {{ item }}
  loop: "{{ flatpak_vaapi_apps }}"
  become: true
  become_user: "{{ ansible_user }}"

- name: Grant Vacuum access on dri for HW acceleration
  shell: |
    flatpak override --user --device=dri rocks.shy.VacuumTube
  become: true
  become_user: "{{ ansible_user }}"