exec --no-startup-id flatpak run rocks.shy.VacuumTube
exec --no-startup-id flatpak run com.github.iwalton3.jellyfin-media-player
exec --no-startup-id flatpak run org.libretro.RetroArch
exec --no-startup-id python3 ~/big_button_exec.py ~/bbe_update_all.json

for_window [app_id="rocks.shy.VacuumTube"] fullscreen enable
for_window [app_id="com.github.iwalton3.jellyfin-media-player"] move to workspace 2
for_window [app_id="org.libretro.RetroArch"] move to workspace 3
for_window [title="^UpdaterButton$"] move to workspace 4

for_window [app_id="rocks.shy.VacuumTube"] fullscreen enable
for_window [app_id="com.github.iwalton3.jellyfin-media-player"] fullscreen enable
for_window [app_id="org.libretro.RetroArch"] fullscreen enable
for_window [title="^UpdaterButton$"] fullscreen enable
