- name: Create sudoers.d file for passwordless apt-get update/upgrade
  ansible.builtin.copy:
    content: |
      {{ tv_user }} ALL=(ALL) NOPASSWD: NOLOG_INPUT: /usr/bin/apt-get update, /usr/bin/apt-get upgrade
    dest: /etc/sudoers.d/99-apt-upgrade
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
