# - name: Configure SDDM autologin
#   ansible.builtin.import_tasks: autologin.yml

- name: Disable lock mechanism
  ansible.builtin.import_tasks: disable_lock.yml

- name: Configure look and feel
  ansible.builtin.import_tasks: look_feel.yml
