- name: Create sway config directory
  file:
    path: "/home/{{ sway_user }}/.config/sway/config.d"
    state: directory
    mode: '0755'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Install sway config
  copy:
    src: config
    dest: "/home/{{ sway_user }}/.config/sway/config"
    mode: '0644'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Install sway autostart config
  copy:
    src: config.d/autostart.conf
    dest: "/home/{{ sway_user }}/.config/sway/config.d/autostart.conf"
    mode: '0644'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Create foot config directory
  file:
    path: "/home/{{ sway_user }}/.config/foot"
    state: directory
    mode: '0755'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Copy foot config
  ansible.builtin.copy:
    src: foot.ini
    dest: "/home/{{ sway_user }}/.config/foot/foot.ini"
    mode: '0755'
    owner: "{{ sway_user }}"
    group: "{{ sway_user }}"

- name: Copy auto login config
  ansible.builtin.copy:
    src: autologin.conf
    dest: "/etc/sddm.conf.d/autologin.conf"
    mode: '0644'