- name: Create sway config directory
  file:
    path: "/home/{{ ansible_user }}/.config/sway/config.d"
    state: directory
    mode: '0755'
    user: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install sway config
  copy:
    src: config
    dest: "/home/{{ ansible_user }}/.config/sway/config"
    mode: '0644'
    user: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install sway autostart config
  copy:
    src: config.d/autostart.conf
    dest: "/home/{{ ansible_user }}/.config/sway/config.d/autostart.conf"
    mode: '0644'
    user: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create foot config directory
  file:
    path: "/home/{{ ansible_user }}/.config/foot"
    state: directory
    mode: '0755'
    user: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy foot config
  ansible.builtin.copy:
    src: foot.ini
    dest: "/home/{{ ansible_user }}/.config/foot/foot.ini"
    mode: '0755'
    user: "{{ ansible_user }}"
    group: "{{ ansible_user }}"